CREATE TABLE CUSTOMER (
	AccountID	INT,
	Fname		VARCHAR(25),
	Lname		VARCHAR(25),
	DateOfBirth	VARCHAR(10),
	Email		VARCHAR(40) NOT NULL,
	UserName	VARCHAR(30) NOT NULL,
	Password	CHAR(60) NOT NULL,
	Card		VARCHAR(24),
	ExpDate		VARCHAR(5),
	SecCode		CHAR(3),
	Street		VARCHAR(100),
	City		VARCHAR(20),
	Zip			CHAR(5),
	State		CHAR(2),
	Phone		CHAR(10),
	PRIMARY KEY	(AccountID)
);

CREATE TABLE ADMIN (
	AccountID	INT,
	Fname		VARCHAR(25),
	Lname		VARCHAR(25),
	DateOfBirth	VARCHAR(10),
	Email		VARCHAR(40) NOT NULL,
	UserName	VARCHAR(30) NOT NULL,
	Password	CHAR(60) NOT NULL,
	Phone		CHAR(10),
	PRIMARY KEY (AccountID)
);

CREATE TABLE PRODUCT (
	ProductID	INT,
	Name		VARCHAR(50) NOT NULL,
	Price		DECIMAL(10, 2) NOT NULL,
	Description	VARCHAR(200),
	Image		VARCHAR(50),
	Visible 	TINYINT(1),
	Num	        INT NOT NULL,
	PRIMARY KEY (ProductID)
);

CREATE TABLE CATEGORY (
	CategoryID	INT,
	Name		VARCHAR(30),
	PRIMARY KEY (CategoryID)
);

CREATE TABLE PRODUCT_OWN_CATEGORY (
	ProductID	INT,
	CategoryID	INT,
	PRIMARY KEY (ProductID, CategoryID),
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE,
	FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE CASCADE
);

CREATE TABLE FOOD_ORDER (
	OrderID		INT,
	AccountID	INT NOT NULL,
	PurchaseDate	VARCHAR(10) NOT NULL,
	TotalPrice	DECIMAL(10, 2) NOT NULL,
	Comments	VARCHAR(200),
	PRIMARY KEY (OrderID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);

CREATE TABLE ORDER_OWN_PRODUCT (
	OrderID		INT,
	ProductID	INT,
	Num 	    INT NOT NULL,
	PRIMARY KEY (OrderID, ProductID),
	FOREIGN KEY (OrderID) REFERENCES FOOD_ORDER(OrderID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAIL (
	OrderID		INT,
	ProductID	INT,
	Name		VARCHAR(50) NOT NULL,
	Price		DECIMAL(10, 2) NOT NULL,
	Num 	    INT NOT NULL,
	PRIMARY KEY (OrderID, ProductID),
	FOREIGN KEY (OrderID) REFERENCES FOOD_ORDER(OrderID) ON DELETE CASCADE
);

CREATE TABLE CART (
	AccountID	INT NOT NULL,
	PRIMARY KEY (AccountID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);

CREATE TABLE CART_OWN_PRODUCT (
	AccountID	INT,
	ProductID	INT,
	Num		INT NOT NULL,
	PRIMARY KEY (AccountID, ProductID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE FAVORITE (
	AccountID	INT NOT NULL,
	PRIMARY KEY (AccountID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);

CREATE TABLE FAVORITE_OWN_PRODUCT (
	AccountID	INT,
	ProductID	INT,
	PRIMARY KEY (AccountID, ProductID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);