DROP TABLE CART, CART_OWN_PRODUCT, FAVORITE, FAVORITE_OWN_PRODUCT;
DROP TABLE ADMIN, ORDER_DETAIL, ORDER_OWN_PRODUCT, PRODUCT_OWN_CATEGORY;
DROP TABLE CATEGORY, FOOD_ORDER, PRODUCT;
DROP TABLE CUSTOMER;